#!/usr/bin/env python3
"""Generate the site's documentation pages from the repository's docs/.

The Markdown in docs/ is the single source of truth. It carries no Hugo front
matter, so that it stays readable on GitHub and in an editor; this script adds
what Hugo needs on the way in.

Run from the website/ directory, or via `make site-content`.
"""

import os
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SOURCE = REPO / "docs"
TARGET = pathlib.Path(__file__).resolve().parent / "content" / "docs"

# Which source file lands where, and in what order. Listing pages explicitly
# rather than globbing keeps the navigation deliberate: a new document appears
# in the sidebar because someone decided where it belongs.
PAGES = [
    # (source, section, slug, title, weight, description)
    #
    # The title is set here rather than taken from the document's first heading.
    # Hugo derives a page's URL from its title unless a slug is given, and an
    # ADR heading like "1. Base the OS on fedora-bootc rather than Fedora
    # CoreOS" makes for an unusable one.
    ("quickstart.md", "guides", "quickstart", "Quick start", 110,
     "From an empty machine to a working Kubernetes node in five steps, with "
     "the mistakes that cost the most time."),
    ("features.md", "reference", "feature-support", "Feature support", 205,
     "What Corium models, what it passes through to k0s, and what it "
     "deliberately does not do."),
    ("reference.md", "reference", "configuration", "Configuration", 210,
     "Every field of the corium: schema, where the configuration comes from, "
     "and what Corium does with it."),
    ("adr/0001-base-image.md", "reference", "adr-0001-base-image",
     "ADR 1 — Base image", 910,
     "Why the operating system is based on fedora-bootc rather than Fedora "
     "CoreOS, and what that trades away."),
    ("adr/0002-root-filesystem.md", "reference", "adr-0002-root-filesystem",
     "ADR 2 — Root filesystem", 920,
     "Why the root filesystem is ext4 rather than xfs, and why the reason is "
     "about who can build the image."),
]

# Links between documents change shape on the site: docs/reference.md becomes
# /docs/reference/configuration/, and a link to a source file has to point at
# GitHub because the site does not serve the repository.
PAGE_URLS = {
    "quickstart.md": "/docs/guides/quickstart/",
    "features.md": "/docs/reference/feature-support/",
    "reference.md": "/docs/reference/configuration/",
    "adr/0001-base-image.md": "/docs/reference/adr-0001-base-image/",
    "adr/0002-root-filesystem.md": "/docs/reference/adr-0002-root-filesystem/",
}

REPO_BLOB = "https://github.com/Corium-OS/Corium/blob/main"


def strip_first_heading(text: str) -> str:
    """Remove the first heading; Doks renders the title from front matter."""
    return re.sub(r"^#\s+.+$\n+", "", text, count=1, flags=re.M)


def rewrite_links(text: str, source: str) -> str:
    """Point links at the site where a page exists, and at GitHub otherwise."""
    source_dir = os.path.dirname(source)

    def replace(match: "re.Match[str]") -> str:
        label, target = match.group(1), match.group(2)

        if target.startswith(("http://", "https://", "#", "mailto:")):
            return match.group(0)

        anchor = ""
        if "#" in target:
            target, anchor = target.split("#", 1)
            anchor = "#" + anchor

        # Resolve the link relative to the document it appears in.
        resolved = os.path.normpath(os.path.join(source_dir, target)) if source_dir else target

        if resolved in PAGE_URLS:
            return f"[{label}]({PAGE_URLS[resolved]}{anchor})"

        # Anything else lives in the repository, not on this site.
        repo_path = os.path.normpath(os.path.join("docs", resolved))
        return f"[{label}]({REPO_BLOB}/{repo_path}{anchor})"

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", replace, text)


def main() -> int:
    if not SOURCE.is_dir():
        print(f"no docs directory at {SOURCE}", file=sys.stderr)
        return 1

    written = 0

    for source, section, slug, title, weight, description in PAGES:
        path = SOURCE / source
        if not path.is_file():
            print(f"missing source document: {path}", file=sys.stderr)
            return 1

        text = path.read_text(encoding="utf-8")
        body = rewrite_links(strip_first_heading(text), source)

        front_matter = (
            "---\n"
            f'title: "{title}"\n'
            f'description: "{description}"\n'
            f'slug: "{slug}"\n'
            "draft: false\n"
            f"weight: {weight}\n"
            "toc: true\n"
            "---\n\n"
            "<!-- Generated by website/sync-docs.py from docs/"
            f"{source}. Edit that file, not this one. -->\n\n"
        )

        destination = TARGET / section / f"{slug}.md"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(front_matter + body, encoding="utf-8")
        print(f"{source} -> content/docs/{section}/{slug}.md")
        written += 1

    print(f"{written} pages generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
